# Generated by Django 4.1 on 2023-11-05 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapDistribution',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution', models.CharField(choices=[('hexagonal', 'Hexagonal'), ('square', 'Manzana'), ('grid', 'Grilla')], default='square', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('streets', models.BooleanField()),
                ('squares', models.BooleanField()),
                ('land_use', models.BooleanField()),
                ('green_area', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('number', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('satelital', models.BooleanField()),
                ('streets', models.BooleanField()),
                ('slider', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mapdistribution')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
            ],
        ),
    ]
