# Generated by Django 4.1 on 2023-12-01 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('streets', models.BooleanField()),
                ('squares', models.BooleanField()),
                ('land_use', models.BooleanField()),
                ('green_area', models.BooleanField()),
                ('amenities', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('number', models.PositiveIntegerField(default=0)),
                ('lego_image', models.ImageField(blank=True, null=True, upload_to='lego/')),
                ('aruco_marker', models.ImageField(blank=True, null=True, upload_to='aruco_markers/')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slider', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='maps/')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
            ],
        ),
    ]
