# Generated by Django 4.1 on 2023-12-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_map_coin_alter_map_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.coin'),
        ),
        migrations.AlterField(
            model_name='map',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.slot'),
        ),
    ]
