
services:
  api:
    container_name: core_api
    build: ./core/.
    volumes:
      - ./core/.:/app
    depends_on:
<<<<<<< Updated upstream
      - db
=======
      - ms_db
    ports:
      - 9900:9900
>>>>>>> Stashed changes
    networks:
      - clbb_core

  db:
    container_name: core_db
    image: postgres:latest
    volumes:
<<<<<<< Updated upstream
      - postgres_data_core:/var/lib/postgresql/data
=======
      - postgres_data_ms:/var/lib/postgresql
>>>>>>> Stashed changes
    networks:
      - clbb_core
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

<<<<<<< Updated upstream
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - clbb_core
=======
  ms_redis:
    image: redis:alpine
    container_name: ms_redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - clbb_ms_network
>>>>>>> Stashed changes


networks:
  clbb_core:
    driver: bridge

volumes:
  postgres_data_core:
