version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./modules:/app/modules
      - ./assets:/app/assets
      - ./backup:/app/backup
      - ./export:/app/export
      - ./logs:/app/logs

