version: '3'
services:
  web:
    container_name: clbb_web
    build: ./api/.
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
       - ./api/.env
    ports:
      - "8500:8000"
    volumes:
      - ./api/:/app/
    depends_on:
      - db
    networks:
      - clbb
  db:  
    container_name: clbb_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: clbb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clbb

networks:
  clbb:
    external: true

volumes:
  postgres_data:


