version: '3'
services:
  clbb-io-modules:
    image: urban_indicators
    container_name: clbb-io-modules
    environment:
      - JUPYTER_TOKEN=""
    ports:
      - "9090:9090"
    volumes:
      - "C:\\Users\\CityLab Biobio - DS\\Dev\\clbb-io\\data:/app/data"
      - "C:\\Users\\CityLab Biobio - DS\\Dev\\clbb-io\\modules:/app/modules"
      - "C:\\Users\\CityLab Biobio - DS\\Dev\\clbb-io\\assets:/app/assets"
      - "C:\\Users\\CityLab Biobio - DS\\Dev\\clbb-io\\backup:/app/backup"
