version: '3'
services:
  web:
    container_name: clbb_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
       - ./.env
    ports:
      - "8500:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: clbb_db
    image: postgres:latest
    environment:
      POSTGRES_DB: clbb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 486s4s89d65a600f2df9862s41f26
