# Generated by Django 4.2 on 2023-10-30 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='data/map/images/')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('number', models.PositiveIntegerField(default=0)),
                ('project', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slider', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=50)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mapbase')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
            ],
        ),
    ]
